stan-core:
  stanPath: .stan
  excludes:
    - CHANGELOG.md
    - docs
    - package-lock.json
  imports:
    entity-client-dynamodb:
      - ../entity-client-dynamodb/.stan/interop/entity-manager/**
      - ../entity-client-dynamodb/.stan/system/stan.requirements.md
      - ../entity-client-dynamodb/.stan/system/stan.todo.md
      - ../entity-client-dynamodb/dist/index.d.ts
    entity-manager-demo:
      - ../entity-manager-demo/.stan/interop/entity-manager/**
      # - ../entity-manager-demo/.stan/system/stan.requirements.md
      # - ../entity-manager-demo/.stan/system/stan.todo.md
      - ../entity-manager-demo/dist/index.d.ts
    entity-tools:
      - ../entity-tools/.stan/interop/entity-manager/**
      # - ../entity-tools/.stan/system/stan.requirements.md
      # - ../entity-tools/.stan/system/stan.todo.md
      - ../entity-tools/dist/index.d.ts
    mock-db:
      - ../mock-db/.stan/interop/entity-manager/**
      # - ../mock-db/.stan/system/stan.requirements.md
      # - ../mock-db/.stan/system/stan.todo.md
      - ../mock-db/dist/index.d.ts
stan-cli:
  cliDefaults:
    run:
      facets: false
      plan: false
      sequential: true
  patchOpenCommand: code -g {file}
  scripts:
    typecheck: npm run typecheck
    lint:
      script: npm run lint:fix
      warnPattern: \\d+:\\d+\\s+warning
    test: npm run test -- --no-color
    build: cross-env NO_COLOR=1 npm run build
    docs:
      script: npm run docs -- --emit none
      warnPattern: \\[warning\\]
    knip: npm run knip
